
import static java.lang.Thread.sleep;
import javax.swing.JOptionPane;


public class Reactions extends javax.swing.JFrame {
    String element1="f";
    String element2="f";
    String element3="f";
    String element4 ="f";
    Equation e=new Equation();
    int rand1,rand2,rand3,rand4;
    
    static int milleseconds = 1000 ;
    static int seconds = 60;
     static int minutes = 1;
     
     static boolean state = true;


    public Reactions() {
        e.GetFromDB();
        String[] choices = new String[4];
        choices[0] = e.getP1();
        choices[1] = e.getP2();
        choices[2] = e.getRandp1();
        choices[3]=e.getRandp2();
        
        initComponents();
        choose4ditincitnums(rand1,rand2,rand3,rand4);
        jButton1.setText(choices[rand1]);
        jButton2.setText(choices[rand2]);
        jButton3.setText(choices[rand3]);
        jButton4.setText(choices[rand4]);
        
        jLabel3.setText("Form the following Drug: "+e.getResult());
         this.setSize(1030,750);
    }
    public void set4nums(int rand1,int rand2, int rand3, int rand4  )
    {
        this.rand1=rand1;
        this.rand2=rand2;
        this.rand3=rand3;
        this.rand4=rand4;
    }
      public void choose4ditincitnums(int n1,int n2, int n3, int n4)
    {
        //int n1,n2,n3,n4;
        while(true)
        {
            n1=Equation.getRandomNumberInRange(0,3);
            n2=Equation.getRandomNumberInRange(0,3);
            n3=Equation.getRandomNumberInRange(0,3);
            n4=Equation.getRandomNumberInRange(0,3);
            if ((n1==n2 || n2==n3 || n1==n3||n1== n4||n2==n4||n3==n4)==false)
                break;
        }
      set4nums(n1,n2,n3,n4);
    }
    public static void StopWatch()
    {
         state = true;
        Thread t = new   Thread ()
        {
            public void run ()
            {
               
                for  ( ; ;)
                {
                    if (state == true)
                    {
                        try
                        {
                           sleep(1);
                           if (milleseconds >1000  )
                           {
                               milleseconds =0;
                               seconds--;
                               
                           }
                           
                            if (seconds <0 && minutes >0)
                           {
                               milleseconds =0;
                               seconds  = 0;
                               minutes --;
                               
                           }
                          jLabel7.setText(":"+milleseconds );
                          milleseconds++;
                          jLabel10.setText(":"+seconds );
                          
                          jLabel6.setText(":" +minutes );
                        
                        }
                        catch (Exception e)
                        {
                            
                        }
                       
                      
                    }
                    else 
                    {
                        break;
                    }
                }
            }
            
        };
        t.start();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(570, 550, 110, 50);

        jLabel9.setBackground(new java.awt.Color(153, 178, 210));
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(320, 540, 380, 90);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 102));
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(350, 540, 80, 70);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 51));
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(460, 560, 100, 30);

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jButton1.setText("NA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 100, 110, 60);

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jButton2.setText("CL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(740, 100, 120, 60);

        jButton3.setBackground(new java.awt.Color(0, 204, 204));
        jButton3.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jButton3.setText("MG");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(530, 100, 120, 60);

        jButton4.setBackground(new java.awt.Color(0, 204, 204));
        jButton4.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jButton4.setText("AL");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(350, 100, 110, 60);

        jButton5.setBackground(new java.awt.Color(238, 215, 42));
        jButton5.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jButton5.setText("back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(30, 630, 240, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 211, 85));
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 480, 560, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1060, 490);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxresdefault.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -60, 1070, 640);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxresdefault.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, -20, 1070, 720);

        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(420, 516, 41, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
       element1=jButton1.getText();
      if ( element4.equals("f")&&element2.equals("f")&&element3.equals("f"))
    {
       JOptionPane.showMessageDialog(this, "select the second element");
    }
    else if ( element2.equals("f")&&!element4.equals("f")&&element3.equals("f"))
    {
          JOptionPane.showMessageDialog(this, "OK");
             this.setVisible(false);
          new mollframe(element4,element1).setVisible(true);
          
     }
      else if ( !element2.equals("f")&&element4.equals("f")&&element3.equals("f"))
    {
          JOptionPane.showMessageDialog(this, "OK");
             this.setVisible(false);
          new mollframe(element2,element1).setVisible(true);
     }
      
      else if ( !element3.equals("f")&&element4.equals("f")&&element2.equals("f"))
    {
          JOptionPane.showMessageDialog(this, "OK");
             this.setVisible(false);
          new mollframe(element3,element1).setVisible(true);
     }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       element2=jButton2.getText();
      if ( element1.equals("f")&&element4.equals("f")&&element3.equals("f"))
    {
       JOptionPane.showMessageDialog(this, "select the second element");
    }
    else if ( element4.equals("f")&&!element1.equals("f")&&element3.equals("f"))
    {
          JOptionPane.showMessageDialog(this, "OK");
             this.setVisible(false);
          new mollframe(element1,element2).setVisible(true);
     }
      else if ( !element4.equals("f")&&element1.equals("f")&&element3.equals("f"))
    {
          JOptionPane.showMessageDialog(this, "OK");
             this.setVisible(false);
          new mollframe(element4,element2).setVisible(true);
     }
      
      else if ( !element3.equals("f")&&element1.equals("f")&&element4.equals("f"))
    {
          JOptionPane.showMessageDialog(this, "OK");
             this.setVisible(false);
          new mollframe(element3,element2).setVisible(true);
     }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     
        element3=jButton3.getText();
      if ( element1.equals("f")&&element2.equals("f")&&element4.equals("f"))
    {
       JOptionPane.showMessageDialog(this, "select the second element");
    }
    else if ( element2.equals("f")&&!element1.equals("f")&&element4.equals("f"))
    {
          JOptionPane.showMessageDialog(this, "OK");
             this.setVisible(false);
          new mollframe(element1,element3).setVisible(true);
     }
      else if ( !element2.equals("f")&&element1.equals("f")&&element4.equals("f"))
    {
          JOptionPane.showMessageDialog(this, "OK");
             this.setVisible(false);
          new mollframe(element2,element3).setVisible(true);
     }
      
      else if ( !element4.equals("f")&&element1.equals("f")&&element2.equals("f"))
    {
          JOptionPane.showMessageDialog(this, "OK");
             this.setVisible(false);
          new mollframe(element4,element3).setVisible(true);
     } 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
  
        element4=jButton4.getText();
      if ( element1.equals("f")&&element2.equals("f")&&element3.equals("f"))
    {
       JOptionPane.showMessageDialog(this, "select the second element");
    }
    else if ( element2.equals("f")&&!element1.equals("f")&&element3.equals("f"))
    {
          JOptionPane.showMessageDialog(this, "OK");
             this.setVisible(false);
          new mollframe(element1,element4).setVisible(true);
     }
      else if ( !element2.equals("f")&&element1.equals("f")&&element3.equals("f"))
    {
          JOptionPane.showMessageDialog(this, "OK");
             this.setVisible(false);
          new mollframe(element2,element4).setVisible(true);
     }
      
      else if ( !element3.equals("f")&&element1.equals("f")&&element2.equals("f"))
    {
          JOptionPane.showMessageDialog(this, "OK");
             this.setVisible(false);
          new mollframe(element3,element4).setVisible(true);
     } 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      new login().setVisible(true);
    this.setVisible(false);//go to login page again
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reactions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
